version: '3'
services:
  backend:
    image: roporos/devops_project
    ports:
      - "8081:8081"
    depends_on:
      - database
    restart: on-failure
  frontend:
    image: roporos/devops_project_front
    ports:
      - "80:80"
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3333:3306"
    restart: unless-stopped



