version: '3'
services:
  prometheus:
    extends:
      file: docker-compose.yml  
      service: backend 
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring

networks:
  monitoring:
