version: '3'
services:

  mysql:
    image: mysql:latest
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: devops
      MYSQL_USER: roporos  
      MYSQL_PASSWORD: root  
    volumes:
      - ./my-datavolume:/var/lib/mysql
    restart: unless-stopped

  backend:
    build:
      context: ./DevOps_Project
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    restart: on-failure

  frontend:
    build:
      context: ./DevOps_Project_Front
    ports:
      - "8089:80"
    depends_on:
      - backend